### ISSUE TITLE
This Repo is not working

### ISSUE THREAD

**Issue by coderaBruce** [junkangwu/BSL#1]
@junkangwu Please make sure your code is runnable from your provided bash command.

**Comment by junkangwu** [comment]
@coderaBruce I apologize for the inconvenience caused. We have made updates to the code, so please feel free to reach out if you encounter any issues.

### Prerequisites
- Python 3.9
- PyTorch 1.11.0

### Training & Evaluation
1. unzip the dataset
```bash
tar -xzvf data/yelp2018.tar.gz -C data
```
2. Reprocude the experiments:
#### Yelp2018 MF
```
cd bash
# SL
bash MF_Frame_pos.sh 1e-4 1e-3 800 1024 0.11 1.00 0 reweight yelp2018 drop
# BSL
bash MF_Frame_pos.sh 1e-4 1e-3 800 1024 0.11 1.10 0 multi yelp2018 drop
```
